2024-05-29 12:35:00,810 - cauldron - INFO - cauldron_app.py - -- Cauldron Application --
2024-05-29 12:35:01,084 - cauldron - INFO - cauldron_app.py - Initializing Cauldron Application
2024-05-29 12:35:01,097 - cauldron - INFO - langchain_util.py - Initializing SQLAgent with model: gpt-4, db_path: sqlite:///sql/recipes_0514_1821.db, verbose: True
2024-05-29 12:35:01,251 - cauldron - INFO - langchain_util.py - Creating SQL Agent with model: gpt-4 and database: <langchain_community.utilities.sql_database.SQLDatabase object at 0x00000212B9DE3530>
2024-05-29 12:35:05,193 - cauldron - INFO - langchain_util.py - SQL Agent created successfully.
2024-05-29 12:35:05,198 - cauldron - INFO - langchain_util.py - SQLAgent initialized successfully.
2024-05-29 12:35:05,199 - cauldron - INFO - cauldron_app.py - SQL Agent Initialized
2024-05-29 12:35:05,200 - cauldron - INFO - langchain_util.py - Initializing ChatBot with model: gpt-4, prompt: blake-goodwyn/cauldron-assistant-v0, temperature: 0.0
2024-05-29 12:35:05,201 - cauldron - INFO - langchain_util.py - Creating chatbot with model: gpt-4, prompt: blake-goodwyn/cauldron-assistant-v0, temperature: 0.0
2024-05-29 12:35:11,532 - cauldron - INFO - langchain_util.py - Chatbot created successfully.
2024-05-29 12:35:11,533 - cauldron - DEBUG - langchain_util.py - Creating StrOutputParser instance.
2024-05-29 12:35:11,534 - cauldron - INFO - cauldron_app.py - UI Agent Initialized
2024-05-29 12:35:11,535 - cauldron - INFO - interactive_demo.py - Initializing Interactive Demo Application
2024-05-29 12:35:11,537 - cauldron - INFO - interactive_demo.py - Serial Port and ADC Constants Initialized
2024-05-29 12:35:12,989 - cauldron - INFO - interactive_demo.py - Voice Interface Initialized
2024-05-29 12:35:12,990 - cauldron - INFO - interactive_demo.py - Grid Layout Initialized
2024-05-29 12:35:12,998 - cauldron - INFO - interactive_demo.py - Text Interaction Components Initialized
2024-05-29 12:35:13,001 - cauldron - INFO - interactive_demo.py - Transcription Components Initialized
2024-05-29 12:35:13,006 - cauldron - ERROR - interactive_demo.py - Error opening serial port: could not open port 'COM4': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
Traceback (most recent call last):
  File "c:\Users\blake\Documents\GitHub\ebakery\cauldron-app\interactive_demo.py", line 84, in __init__
    self.ser = serial.Serial(self.SERIAL_PORT, self.BAUD_RATE)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Python312\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Python312\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM4': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-05-29 12:35:13,016 - cauldron - WARNING - interactive_demo.py - Serial connection could not be established.
2024-05-29 12:35:13,016 - cauldron - INFO - cauldron_app.py - Cauldron Application Initialized
